
# catalog-info.yml
# This file contains metadata for backstage
# Read more about available fields and annotations:
# https://github.com/tradeshift/backstage
#
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: s3gof3r
  description: |
    s3gof3r module
  annotations:
    github.com/project-slug: Tradeshift/s3gof3r # GitHub project name

spec:
  type: other
  owner: platform-ops
  lifecycle: experimental
